### PR TITLE
feat(inputs): permissions

### PR DESCRIPTION
**Pull request by ragnarpa**

### CODE REVIEW

**Comment by gr2m** [comment]
We don't want to implement permissions as a single object, but as separate keys, as described here: https://github.com/actions/create-github-app-token/issues/3

We want these keys to be automatically kept up to date based on new releases of https://github.com/octokit/app-permissions, which we can implement via actions and https://github.com/apps/octokit-release-notifier

**Comment by ragnarpa** [comment]
> We don't want to implement permissions as a single object, but as separate keys, as described here: #3
> 
> We want these keys to be automatically kept up to date based on new releases of https://github.com/octokit/app-permissions, which we can implement via actions and https://github.com/apps/octokit-release-notifier

@gr2m, when can we expect #3 to be released?

**Comment by gr2m** [comment]
we should be unblocked since https://github.com/octokit/app-permissions/releases/tag/v2.0.0

**Comment by martincostello** [comment]
Any chance on this being released soon if it's unblocked? I'd like to consume the changes to move into this action from a third-party one.

**Comment by gr2m** [comment]
sorry we have been busy with other projects, I cannot give you an ETA when we get to finish up this work. The current pull request cannot be merged as is, my concerns from above (https://github.com/actions/create-github-app-token/pull/111#issuecomment-1975373214) have not been addressed yet. We don't want a single `permissions` parameter, but separate `permission_{permission_name}` keys, e.g. `permission_issues`. And we want these to be auto-generated based on https://github.com/octokit/app-permissions/

**Comment by ragnarpa** [comment]
Hi all. Sorry, but I do not have enough resources to address the aforementioned concerns in this pull request. As this pull won't me merged as it is then I'll close it.

**Pull request closed without merging**
